name: dio_cache_interceptor_hive_store
description: A DB cache store implementation with Hive for dio_cache_interceptor package.
homepage: https://github.com/llfbandit/dio_cache_interceptor/tree/master/dio_cache_interceptor_hive_store
version: 3.2.1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  dio_cache_interceptor: 
    path : ../dio_cache_interceptor

  # https://pub.dev/packages/hive
  hive: ^3.0.0-dev ## active (hivedb.dev)

# dependency_overrides:
#   dio_cache_interceptor:
#     path: ../dio_cache_interceptor

dev_dependencies:
  # https://pub.dev/packages/lints
  lints: ^2.0.1 ## active
  # https://pub.dev/packages/test
  test: ^1.23.1 ## active
